### ISSUE TITLE
ISO_8601 duration format

### ISSUE THREAD

**Issue by ShinDarth** [MHzarini/angular2-time-duration-picker#2]
Is there a way to convert the result to [ISO_8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations) ?

**Comment by MHzarini** [comment]
you can use [moment-isoduration](https://github.com/dordille/moment-isoduration) to convert the value in `onChange` output function.

**Comment by ShinDarth** [comment]
@MHzarini Thanks. However, it would be nice if its logic can be included into this component, so no extra libraries need to be imported.
